# This file was generated by GoReleaser. DO NOT EDIT.
cask "myschema" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "fec72f7887be1146d9843816740bbc0a1837c3f5e6ab19f44e927085248dbe79"
      url "https://github.com/winebarrel/myschema/releases/download/v#{version}/myschema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7bdcf15fd12309c96574d167832c95e22e9cd49846f79b1a1cd7eca97718899"
      url "https://github.com/winebarrel/myschema/releases/download/v#{version}/myschema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cca1a91525a92b4f680ba7da9029f6cfa47eecc3a0b40817a95d4743422cdc99"
      url "https://github.com/winebarrel/myschema/releases/download/v#{version}/myschema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bafe2c9d7489bcef79f6f21f8556fc5d7d9d01093b0bc00794fac1a5d6ae3870"
      url "https://github.com/winebarrel/myschema/releases/download/v#{version}/myschema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "myschema"
  desc "myschema is a declarative schema management tool for MySQL."
  homepage "https://github.com/winebarrel/myschema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "myschema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/myschema"]
    end
  end

  # No zap stanza required

end
